package com.devstree.project.utils;

public interface Contants {

    String PACKAGE_NAME = "com.devstree.project";
    String RECEIVER = PACKAGE_NAME + ".RECEIVER";
    String RESULT_DATA_KEY = PACKAGE_NAME + ".RESULT_DATA_KEY";
    String LOCATION_LAT_EXTRA = PACKAGE_NAME + ".LOCATION_lAT_EXTRA";
    String LOCATION_LNG_EXTRA = PACKAGE_NAME + ".LOCATION_LNG_EXTRA";
    String SELECTED_ADDRESS = PACKAGE_NAME + ".SELECTED_ADDRESS";
    String LANGUAGE = PACKAGE_NAME + ".LANGUAGE" ;

    String API_KEY = PACKAGE_NAME + ".API_KEY";
    String LIST_DATA = PACKAGE_NAME + ".LIST_DATA";
    String LATLNG_DATA = PACKAGE_NAME + ".LATLNG";
    String ROUTE_ONLY = PACKAGE_NAME + ".ROUTE_ONLY";
    String COUNTRY = PACKAGE_NAME + ".COUNTRY";
    String SUPPORTED_AREAS = PACKAGE_NAME + ".SUPPORTED_AREAS";

    int SUCCESS_RESULT = 0;
    int FAILURE_RESULT = 1;
    int SELECT_LOCATION_REQUEST_CODE = 22;
}

